### ISSUE TITLE
eliminate vulnerability issues

### ISSUE THREAD

**Issue by jtrs** [cubbles/cubx-wct-scaffolder#4]
Update version of 
* [x] mocha#5.2.0
* [x] chai#4.1.2
* [x] sinon#6.1.5
* [x] sinon-chai#3.2.0
* [x] esint#5.4.0
* [x] eslint-config-standard#5.3.5
* [x] eslint-plugin-promise#1.3.2
* [x] eslint-plugin-standard#1.3.3
* [x] command-line-args#3.0.5
* [x] inquirer#3.3.0
* [x] mustache#2.3.2
* [x] winston#2.4.4
